spring:
  application:
    name: facebook-mock
server:
  port: 9800
  compression:
    enabled: on
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    protocol_header: x-forwarded-proto
  use-forward-headers: true

